### ISSUE TITLE
Pinterest clickable objects and their retrieved products downloading

### ISSUE THREAD

**Issue by zeynepgokce** [ataknkcyn/pinterest-crawler#1]
Merhaba Atakan,

Paylaşımın için teşekkürler. Kodu rahatlıkla çalıştırabildim.

Web hakkında hiçbir bilgisi olmayan biri olark soruyorum. 

Aşağıdaki linkte, pinterest'in visual search ile ilgili örneği var. Ben bir image üzerindeki tıklanabilir nesnelere tıkladığımda, Pinterest bu nesnelere en benzer ürünleri getiriyor. Bu image üzerindeki her bir tıklanabilir nesne ile ilişkili getirilen diğer nesnelere sırayla nasıl erişebilirim? Bunları nasıl indirebilirim? Nerden başlayabilirim? 

Yardımların için şimdiden çok teşekkürler.

https://tr.pinterest.com/pin/327777679144798211/visual-search/?x=233&y=609&w=154&h=231&cropSource=4&imageSignature=aa06f0bbe0d6aaf10229ab57542033b0

**Comment by ataknkcyn** [comment]
Daha iyi anlayabilmek icin soruyorum. Attiginiz linkte ornek gorsel uzerinde secilmis alanin sag tarafinda kalan gorselleri mi indirmek istiyorsunuz?

**Comment by zeynepgokce** [comment]
Merhaba, 
Evet tam olarak anladığınız gibi. Ekrandaki query image üzerinde seçilebilir noktalar var. Bu noktaların her biri için sağ tarafta açılan görsellerin bilgilerini ve kendilerini indirmek istiyorum. 
![Screenshot from 2023-03-12 17-48-48](https://user-images.githubusercontent.com/12368150/224553426-316200e1-2af3-4103-8dba-689b893f6928.png)

**Comment by ataknkcyn** [comment]
Aktif olarak gelistirmeye devam ettigim bir proje olmadigi icin musait bir zamanda bakmaya calisicagim.
